import { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Col, Spin } from "antd";

import { useDispatch, useSelector } from "react-redux";

import PokemonList from "../src/components/PokemonList";
import { fetchPokemonsDetails } from "../src/redux/slices/PolemonsSlice";
import InputSearch from "../src/components/InputSearch";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { list, listFilters } = useSelector(
    (state: any) => state.PokemonsSlice
  );

  useEffect(() => {
    dispatch(fetchPokemonsDetails() as any);
  }, []);

  return (
    <div>
      <Head>
        <title>PokeNux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Col span={4} offset={10} className="Logo">
          <img src="logo.svg" alt="logo" />
        </Col>
        <Col span={8} offset={8} className="SearchPokemon">
          <InputSearch />
        </Col>
        <Col span={24} style={{ textAlign: "center" }}>
          {list.loading ? (
            <Spin spinning={list.loading} tip="Cargando" />
          ) : (
            <PokemonList
              pokemons={listFilters.length ? listFilters : list.data}
            />
          )}
        </Col>
      </main>
    </div>
  );
};

export default Home;
